name: django-react-boilerplate CI

on:
  push:
    branches: [ "master", "setup-github-actions" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint-test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m install poetry
          python -m poetry install
      - name: Run Python Lint and Tests
        run: |
          cd src
          flake8 .
          python manage.py test main

  lint-test-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install JS Dependencies
        run: |
          cd src/frontend
          npm i -g yarn
          yarn install
      - name: Run JS Lint and Tests
        run: |
          yarn lint
          yarn test

  build:
    needs: [lint-test-python, lint-test-js]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install poetry
          python -m poetry install
      - name: Set up Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install JS Dependencies
        run: |
          cd src/frontend
          npm i -g yarn
          yarn install
      - name: Build JS
        run: |
          yarn build
      - name: Setup JS build with Django App
        run: |
          cd ../
          python manage.py collectstatic